name: cook
description: Cooking application
publish_to: 'Mas aurelien'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  cloud_firestore: ^3.1.6
  firebase_auth: ^3.3.5
  firebase_storage: ^10.2.7
  email_validator: '^2.0.1'

  flutter_spinkit: ^5.1.0
  page_transition: ^2.0.4
  google_fonts: 2.2.0
  ionicons: ^0.1.2
  simple_animations: ^4.0.1
  image_picker: ^0.8.4+9
  sliding_up_panel: ^2.0.0+1
  dots_indicator: ^2.1.0
  flutter_zoom_drawer: ^2.3.1
  path_provider: ^2.0.9
  cached_network_image: ^3.2.0
  form_builder_image_picker: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/ingredients/
